print("=== Original Needham-Schroeder Session ===\n")

# Session key generated by server
K_AB = "SESSIONKEY123"

# Ticket for Bob
message3 = "Ticket_for_Bob_encrypted_with_KBS"

print("Alice -> Server: Request session with Bob")
print("Server -> Alice: Sends session key K_AB")

print("Alice -> Bob: Sends Message 3 (ticket)")
print("Message 3:", message3)

# Bob challenge
Nb = 100
print("Bob challenge:", Nb)

print("Alice responds:", Nb - 1)

print("Authentication Successful\n")